[package]
name = "snak"
version = "0.1.0"
edition = "2024"
authors = ["realdanvanth <realdanvanth@gmail.com>"]
description = "snake game"
license = "MIT"
repository = "https://github.com/realdanvanth/rsnake"
[dependencies]
crossterm = "0.29.0"
rand = "0.9.2"
